using AutoTest.Abstractions;
using System.Diagnostics;
using System.Text.Json;
namespace AutoTest.Mqtt;

public sealed class MqttStepExecutor : ITestStepExecutor
{
    private readonly MqttTestClient client;
    public MqttStepExecutor(IEnvironmentStore environment)=>client=new(environment);
    public string Name => "mqtt";
    public bool CanExecute(StepSpec step) => step.Request?.Mqtt is not null;
    public async Task<StepRunResult> ExecuteAsync(StepExecutionContext c,CancellationToken ct){var watch=Stopwatch.StartNew();var step=c.Step;var r=step.Request!.Mqtt!;string action=r.Action.ToLowerInvariant();string topic=Topic(r.Topic,c);string payload=Templates.Resolve(r.Payload??"",c.Variables,c.Environment);int qos=r.Qos??1;bool retain=r.Retain??false;int timeout=r.TimeoutMs??c.Environment.Int("MQTT_TIMEOUT_MS",10000);string? user=Optional(r.Username,c),password=Optional(r.Password,c),clientId=Optional(r.ClientId,c);string expected=Expected(step.Expect,c);string? actual=null;try{if(timeout<=0)throw new InvalidOperationException("MQTT timeoutMs phải lớn hơn 0.");if(qos is <0 or >2)throw new InvalidOperationException("MQTT QoS chỉ hỗ trợ các giá trị 0, 1 hoặc 2.");MqttReceivedMessage? received;switch(action){case"connect":await client.ConnectAsync(user,password,clientId,ct);received=null;break;case"publish":await client.PublishAsync(topic,payload,qos,retain,user,password,clientId,ct);received=null;break;case"subscribe":received=await client.SubscribeAsync(topic,qos,TimeSpan.FromMilliseconds(timeout),user,password,clientId,ct);break;case"roundtrip":received=await client.RoundtripAsync(topic,payload,qos,retain,TimeSpan.FromMilliseconds(timeout),user,password,clientId,ct);break;case"lastwill":if(r.Will is null)throw new InvalidOperationException("Thao tác MQTT lastwill yêu cầu object will.");topic=Topic(r.Will.Topic,c);if(topic.Length==0)throw new InvalidOperationException("MQTT will.topic không được để trống.");qos=r.Will.Qos??1;payload=Templates.Resolve(r.Will.Payload??"",c.Variables,c.Environment);retain=r.Will.Retain??false;received=await client.LastWillAsync(topic,payload,qos,retain,TimeSpan.FromMilliseconds(timeout),user,password,clientId,(name,value)=>c.ReportIntermediate?.Invoke(new(name,c.Cleanup,true,"MQTT LASTWILL",topic,null,"Giai đoạn phải hoàn thành thành công",null,value,watch.Elapsed,null)),ct);break;default:throw new InvalidOperationException($"Không hỗ trợ thao tác MQTT: {r.Action}");}actual=received is null?"Đã thực hiện thành công.":JsonSerializer.Serialize(new{received.Topic,received.Payload});if(c.Assertions&&received is not null)Assert(step.Expect?.Mqtt,received,c);return new(step.Name,c.Cleanup,true,$"MQTT {action.ToUpperInvariant()}",topic,payload.Length==0?null:R(c,payload),expected,null,actual,watch.Elapsed,null);}catch(Exception ex){return new(step.Name,c.Cleanup,false,$"MQTT {action.ToUpperInvariant()}",topic,payload.Length==0?null:R(c,payload),expected,null,actual,watch.Elapsed,R(c,ex.Message));}}
    private static string? Optional(string? v,StepExecutionContext c)=>string.IsNullOrWhiteSpace(v)?null:Templates.Resolve(v,c.Variables,c.Environment);
    private static string Topic(string? v,StepExecutionContext c){string value=Templates.Resolve(v??"",c.Variables,c.Environment).Trim('/');string prefix=(c.Environment.Get("MQTT_PREFIX")??"").Trim('/');return value.Length==0?"":prefix.Length==0||value==prefix||value.StartsWith(prefix+"/",StringComparison.Ordinal)?value:$"{prefix}/{value}";}
    private static void Assert(MqttExpectSpec? e,MqttReceivedMessage a,StepExecutionContext c){if(e?.Topic is { } t&&a.Topic!=Topic(t,c))throw new InvalidOperationException("Topic MQTT nhận được không đúng như mong đợi.");if(e?.Payload is { } p&&a.Payload!=Templates.Resolve(p,c.Variables,c.Environment))throw new InvalidOperationException("Nội dung MQTT nhận được không đúng như mong đợi.");if(e?.PayloadContains is { } x&&!a.Payload.Contains(Templates.Resolve(x,c.Variables,c.Environment),StringComparison.Ordinal))throw new InvalidOperationException("Nội dung MQTT không chứa giá trị mong đợi.");}
    private static string Expected(ExpectSpec? e,StepExecutionContext c){if(!c.Assertions)return"Bước dọn dữ liệu MQTT";if(e?.Mqtt is null)return"Thao tác MQTT hoàn thành thành công";var l=new List<string>();if(e.Mqtt.Topic is { } t)l.Add($"Topic nhận được = {Topic(t,c)}");if(e.Mqtt.Payload is { } p)l.Add($"Nội dung nhận được = {Templates.Resolve(p,c.Variables,c.Environment)}");return string.Join("\n",l);}
    private static string R(StepExecutionContext c,string v)=>c.Redact?.Invoke(v)??v;
    public ValueTask DisposeAsync()=>client.DisposeAsync();
}


