<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><ProjectReference Include="..\..\src\AutoTest.Abstractions\AutoTest.Abstractions.csproj" /><ProjectReference Include="..\..\src\AutoTest.Core\AutoTest.Core.csproj" /><ProjectReference Include="..\..\src\AutoTest.Http\AutoTest.Http.csproj" /><ProjectReference Include="..\..\src\AutoTest.PostgreSql\AutoTest.PostgreSql.csproj" /><ProjectReference Include="..\..\src\AutoTest.Mqtt\AutoTest.Mqtt.csproj" /></ItemGroup></Project>
