<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /><ProjectReference Include="..\AutoTest.Integration.Abstractions\AutoTest.Integration.Abstractions.csproj" /><ProjectReference Include="..\AutoTest.Integration.Artifacts\AutoTest.Integration.Artifacts.csproj" /></ItemGroup></Project>
