<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><ProjectReference Include="..\..\src\AutoTest.Integration.Abstractions\AutoTest.Integration.Abstractions.csproj" /><ProjectReference Include="..\..\src\AutoTest.Integration.Artifacts\AutoTest.Integration.Artifacts.csproj" /><ProjectReference Include="..\..\src\AutoTest.Integration.Http\AutoTest.Integration.Http.csproj" /></ItemGroup></Project>
