<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AutoTest.Abstractions\AutoTest.Abstractions.csproj" />
    <ProjectReference Include="..\AutoTest.Http\AutoTest.Http.csproj" />
    <ProjectReference Include="..\AutoTest.PostgreSql\AutoTest.PostgreSql.csproj" />
    <ProjectReference Include="..\AutoTest.Mqtt\AutoTest.Mqtt.csproj" />
  </ItemGroup>
</Project>
